### ISSUE TITLE
resource pack issue and a small suggestion

### ISSUE THREAD

**Issue by The-Nyla** [FentisDev/PortalGun#1]
![image](https://user-images.githubusercontent.com/79489385/135938802-d88a3140-7362-4ba4-a80f-201de1704f17.png)

small issue when using the oraxen resource pack separately, when merging the packs it doesn't work at all.

Also it would be nice to keep the player's momentum through the portals ( so you can do the fun jumps and stuff)

**Comment by Creeperz653** [comment]
prob has to do with your merge

**Comment by FentisDev** [comment]
I've been thinking about how to solve this problem, would it be better if I put the Material and the CustomModelData in the plugin's config? so they could edit this information in resourcepack to work on plugins like ItemsAdder and Oraxen, would that be enough?

**Comment by The-Nyla** [comment]
Yep, that would work perfectly! the main issue seems to be that the oraxen pack also uses wooden hoes for alot of the items, and the .json files for your pack, and oraxen conflict

**Comment by FentisDev** [comment]
Alright I'm working on it, but I want to do some more tests before posting.

"Also it would be nice to keep the player's momentum through the portals (so you can do the fun jumps and stuff)"

This is a bit tricky to do as the player tends to lose his speed when he hits the block behind the portal... there is actually this feature in the plugin, but you have to be lucky enough to be teleporting before hitting the ground.
