### ISSUE TITLE
Bug of dupilaction !!

### ISSUE THREAD

**Issue by YassiGame** [FentisDev/PortalGun#3]
When you drop the portal gun and you switch the slot, he will replace de slot in a portal gun and you will still have the portal gun from before

**Comment by FentisDev** [comment]
Oh yes, I'm already fixing it! Thanks a lot for the report!

**Comment by YassiGame** [comment]
The portal gun you can't drop it in inventory panel :(

here is the video (sorry for the quality of the video)
https://youtu.be/_JRvnIo25tI

**Comment by YassiGame** [comment]
> Oh yes, I'm already fixing it! Thanks a lot for the report!

Ah okay thanks a lot because i love this plugin

**Comment by YassiGame** [comment]
You can use the switch button the f key (he switch the item in the other hand) when you have the portal gun in hand you can prevent the action before executated is beter than drop it

sorry for my english

**Comment by YassiGame** [comment]
https://www.spigotmc.org/resources/fkeycommand.62655/ 
there is a exemple and this feature work in 1.12.2/1.18.1

**Comment by FentisDev** [comment]
Yes I thought about the possibility of using the F key but I still want to make a system for picking up and transporting entities and blocks in the future.
With this bug I'm coming across other bugs related to the drop, I'll see what I can do to make the system fully functional. Thanks again for your report.
Don't worry about translations! I do not speak English too 😄

**Comment by FentisDev** [comment]
Done! It's now available on Spigot! Please if you can leave a review on Spigot's page I would be very grateful! Thanks again for the report.
